### ISSUE TITLE
FileLink provider for WebDav

### ISSUE THREAD

**Issue by ghost** [thunderbird/webdav-filelink#1] opened 2019-10-23 14:17 UTC
Hello,

Formerly I allready used the webdav-filelink addon, until Thunderbird upgraded its internal code and it did not work anymore.
So I was quite happy when I saw your updated addon.
Unfortunately, I can not get it work.
- In cPanel, I created a webdisk account
- The serverpath is identical to what I formerly had:  https://user%40domain:password@schieres.lu:2078/
- When I try to send a message, after clicking on "link": "Unable to upload file.pdf to WebDAV"
- When I enter the serverpath into Firefox, I can access the folder without problem ...
- When I check stored passwords in Thunderbird, it is not stored, so the error happens on a stage before...
Any idea ? Thanks,
Paul Schieres / Luxembourg / paul@schieres.lu

**Comment by darktrojan** [comment] 2019-10-23 21:23
Have you tried putting just https://schieres.lu:2078/ ? It will ask you for a username and password.

**Comment by Go-rom** [comment] 2019-12-03 17:27
Hello,

i have the same issue with Thunderbird 68.2.2 and FileLink provider for Webdav (V2).

If i put only https://_mynextcloudserver_/ , Thunderbird doesn't ask a username and password.

But if i put https://_mynextcloudserveur_/remote.php/dav/, it does but it won't accept my credentials.
TOTP is activated so i created an app password but i've got the same error message "Unable to upload file.pdf to WebDAV"

Could you please provide a small HowTo in order to make this addon working ?

Thank you

**Comment by manu-p** [comment] 2019-12-11 15:51
Hi all, 

TB 68.2.1
NC 17.0.1

I've been able to specify a **Private URL** https://cloud.domain/remote.php/webdav/Mail-attachments/ and attachments are well stored in this Mail-attachments folder as required.

Now, the question is what am I supposed to mention as **Public URL**? 
It just can't be the previous Private URL since it is... private and requires a user/pass to access the attachment. 
So I publicly shared the Mail-attachments folder in NC, got the link, something like https://cloud.domain/index.php/s/agz7QWblablaf4pM5/ (just had to add the trailing /) and tried it as **Public URL**... for no luck: the login box is displayed instead of the file.

So, as already asked above, would it be possible to get more information, if not a guide/documentation, on what's got to be mentioned in these 2 fields? Especially the 2nd one, the **Public URL**. Thanks.

**Comment by darktrojan** [comment] 2019-12-11 21:50
The public and private URLs are different, depending on which server software you use and how it is set up. If you don't know them, I can't help you.

What I can tell you is that this software assumes the name of the file you upload is kept in tact and added to the end of the public URL you specify.

**Comment by Go-rom** [comment] 2019-12-13 11:00
Hello @darktrojan 

Have you personally test it with NextCloud ?

Thank you

**Comment by manu-p** [comment] 2019-12-14 14:03
OK, let's forget NextCloud for a while, until a new TB compatible module for NC is released again.

I found another webDav server included in one of my ionos hostings. Fine! 
It's called HiDrive.
The WebDav URL is given as : https://webdav.hidrive.ionos.com/
After some testing, I found the correct **Public URL** is https://webdav.hidrive.ionos.com/users/myHiDriveAccount/Mail-attachment/ where _myHiDriveAccount_ is the account I've created for this ionos HiDrive.

And it works! Big mail attachment files are uploaded there after I give user/pass when asked.

Then remains the question for this **Public URL**... I had the idea I just had to share this Mail-attachment subfolder thru the HiDrive web interface and it would to the trick!
I mean, the generated sharing link looks like https://hidrive.ionos.com/share/blabla-9r8 and that's what I copy/pasted in the **Public URL** and that's what I see in the mail, I mean something like: 
. . .
https://hidrive.ionos.com/share/blabla-9r8/thebigimagefile.jpg

But when I click in this link, I just go to a page which URL is https://hidrive.ionos.com/share/blabla-9r8/thebigimagefile.jpg, telling me:

> **Not Found**
> 
> The requested URL /share/blabla-9r8/thebigimagefile.jpg was not found on this server.

So I just tried to remove the end of this URL, just the file part "thebigimagefile.jpg" to see if I keep visiting the shared subfolder, and yes!, apart that the URL is rewritten to https://hidrive.ionos.com/share/blabla-9r8#$/... See these new **#$/** at the end?

I then had the idea to add these #$/ at the end of the **Public URL** in the module. And the result is now that I'm reaching https://hidrive.ionos.com/share/sqrh4j-9r8#$/thebigimagefile.jpg where I can see an unclickable thebigimagefile.jpg **file name**, with **no other** possibility than move up to the https://hidrive.ionos.com/share/blabla-9r8#$ folder (and find all previously shared big attachment files which is definitely not what I would expect!!!) and a message in the middle of the page saying something like:

> An error occurred while loading /thebigimagefile.jpg.

I'm beginning to feel like frustrated with this module, just wondering if I can really get it working with the webdav solutions I have... :-/

Meanwhile, TB proposes **WeTranfer** for this purpose and it's just working right. Unfortunately, this is not the solution I want to use... Nor dropbox and all those so called "services".

**Comment by ploink** [comment] 2021-03-17 13:44
Thunderbird is not asking me for a username/password.
When I try to upload, I get "Unable to upload <filename> to WebDAV". Then when I check the server log, there is only one request: "401 Unauthorized".

For now I configured the server to grant me ip-based access without login and everything works fine then.

Using Thunderbird 78.8.0 on Fedora Linux.

**Comment by Go-rom** [comment] 2021-03-17 14:03
Hello @ploink 

Is it about Nextcloud ?

**Comment by ploink** [comment] 2021-03-17 17:23
@Go-rom Not specifically. I am using apache with simple DAV config, but I have tried to debug this problem en the issue seems to be in the password prompt dialog, independent of what server you are using.
Some things have changed in TB that break it. If you have stored the password before Mozilla made the changes, I suppose the addon keeps working.

**Comment by thedaveCA** [comment] 2021-04-23 02:09
This is broken here as well, and while a "me too" doesn't help, I can offer a test account to any developer who needs one, just reach out or comment here.

**Comment by thedaveCA** [comment] 2021-04-23 02:16
Oh, and a workaround! Install the [BrowseInTab](https://addons.thunderbird.net/en-US/thunderbird/addon/browseintab/) add-on, and visit your WebDAV publish URL, you will be prompted for credentials. Enter your WebDAV credentials, close the tab, and try FileLink again, it should work.

This confirms the add-on works, and the issue is just relating to setting up authentication. I have not had success trying to force credentials into the URL or anything else.

**Comment by danielfomin96** [comment] 2021-09-28 21:54
I have the same problem that no login prompt is displayed. In the developer console I get the following error:
```
Exception { name: "NS_ERROR_NOT_AVAILABLE", message: "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannelInternal.remoteAddress]", result: 2147746065, filename: "resource://devtools/server/actors/network-monitor/network-observer.js", lineNumber: 1043, columnNumber: 0, data: null, stack: "_onResponseHeader@resource://devtools/server/actors/network-monitor/network-observer.js:1043:5\n_dispatchActivity@resource://devtools/server/actors/network-monitor/network-observer.js:620:14\nNetworkObserver.prototype.observeActivity<@resource://devtools/server/actors/network-monitor/network-observer.js:729:12\nexports.makeInfallible/<@resource://devtools/shared/ThreadSafeDevToolsUtils.js:103:22\n", location: XPCWrappedNative_NoHelper }
ThreadSafeDevToolsUtils.js:82:13
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: jar:file:///home/user/.thunderbird/fsd8sfs.default-release/extensions/dav-cloudfile@darktrojan.net.xpi!/api/authRequest.js :: getAuthHeader :: line 81"  data: no] authRequest.js:81:30
WebExtensions: Error: An unexpected error occurred
    normalizeError resource://gre/modules/ExtensionCommon.jsm:755
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:903
ext-cloudFile.js:146
Prompter: internal dialogs not available in this context. Falling back to window prompt. Prompter.jsm:1084
    set modalType resource://gre/modules/Prompter.jsm:1084
    ModalPrompter resource://gre/modules/Prompter.jsm:1040
    pickPrompter resource://gre/modules/Prompter.jsm:44
    confirmEx resource://gre/modules/Prompter.jsm:304
    uploadCloudAttachment chrome://messenger/content/messengercompose/MsgComposeCommands.js:2300
    AsyncFunctionThrow self-hosted:696
```

Forcing credentials into the URL probably won't work because this method is deprecated as it is regarded to be unsecure: [https://medium.com/@lmakarov/say-goodbye-to-urls-with-embedded-credentials-b051f6c7b6a3](https://medium.com/@lmakarov/say-goodbye-to-urls-with-embedded-credentials-b051f6c7b6a3)

**Comment by darktrojan** [comment] 2021-09-28 22:12
`[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIStringBundle.GetStringFromName]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: jar:file:///home/user/.thunderbird/fsd8sfs.default-release/extensions/dav-cloudfile@darktrojan.net.xpi!/api/authRequest.js :: getAuthHeader :: line 81"  data: no] authRequest.js:81:30`

Interesting @danielfomin96, that's the "this string doesn't exist" error, but it certainly does. What Thunderbird version are you using?

**Comment by danielfomin96** [comment] 2021-09-28 22:14
I am using version 91.1.1 on Arch Linux.

**Comment by darktrojan** [comment] 2021-09-28 23:36
The missing string error should be fixed now (pending approval on the add-ons website). I don't know if that's the whole cause of everything in this issue but I'm closing it because I don't want to see it any more.

**Closed as completed by darktrojan** 2021-09-28 23:36 UTC

**Comment by hidriveuser** [comment] 2022-04-11 20:09
> OK, let's forget NextCloud for a while, until a new TB compatible module for NC is released again.
> 
> I found another webDav server included in one of my ionos hostings. Fine! It's called HiDrive. The WebDav URL is given as : https://webdav.hidrive.ionos.com/ After some testing, I found the correct **Public URL** is https://webdav.hidrive.ionos.com/users/myHiDriveAccount/Mail-attachment/ where _myHiDriveAccount_ is the account I've created for this ionos HiDrive.
> 
> And it works! Big mail attachment files are uploaded there after I give user/pass when asked.
> 
> Then remains the question for this **Public URL**... I had the idea I just had to share this Mail-attachment subfolder thru the HiDrive web interface and it would to the trick! I mean, the generated sharing link looks like https://hidrive.ionos.com/share/blabla-9r8 and that's what I copy/pasted in the **Public URL** and that's what I see in the mail, I mean something like: . . . https://hidrive.ionos.com/share/blabla-9r8/thebigimagefile.jpg
> 
> But when I click in this link, I just go to a page which URL is https://hidrive.ionos.com/share/blabla-9r8/thebigimagefile.jpg, telling me:
> 
> > **Not Found**
> > The requested URL /share/blabla-9r8/thebigimagefile.jpg was not found on this server.
> 
> So I just tried to remove the end of this URL, just the file part "thebigimagefile.jpg" to see if I keep visiting the shared subfolder, and yes!, apart that the URL is rewritten to https://hidrive.ionos.com/share/blabla-9r8#$/... See these new **#$/** at the end?
> 
> I then had the idea to add these #$/ at the end of the **Public URL** in the module. And the result is now that I'm reaching https://hidrive.ionos.com/share/sqrh4j-9r8#$/thebigimagefile.jpg where I can see an unclickable thebigimagefile.jpg **file name**, with **no other** possibility than move up to the https://hidrive.ionos.com/share/blabla-9r8#$ folder (and find all previously shared big attachment files which is definitely not what I would expect!!!) and a message in the middle of the page saying something like:
> 
> > An error occurred while loading /thebigimagefile.jpg.
> 
> I'm beginning to feel like frustrated with this module, just wondering if I can really get it working with the webdav solutions I have... :-/
> 
> Meanwhile, TB proposes **WeTranfer** for this purpose and it's just working right. Unfortunately, this is not the solution I want to use... Nor dropbox and all those so called "services".

I've just uploaded a file to my IONOS HiDrive using WebDAV and Thunderbird  91.7.0 and FileLink provider for WebDav 4 after hours of experimentation, and have succeeded!!!! with the following settings.

Firstly I mapped a network drive to my desktop using instructions here (which didn't work as explained!!)
[https://www.ionos.co.uk/help/hidrive/setting-up-hidrive-on-your-devices/connect-to-hidrive-using-webdav/](https://www.ionos.co.uk/help/hidrive/setting-up-hidrive-on-your-devices/connect-to-hidrive-using-webdav/)
and asking it to remember my credentials. Presumably if I had NOT ticked that box I would be asked to enter the credentials when accessing via Thunderbird.
whether this made a difference I don't know. I also followed the instructions near the bottom of the page for fixing a slow WebDAV connection.

In Thunderbird Preferences - Attachment section, I highlighted the WebDav entry and for Private url I entered:
[https://webdav.hidrive.ionos.com/users/username/](https://webdav.hidrive.ionos.com/users/username/)
and for the public url
[https://hidrive.ionos.com/lnk/](https://hidrive.ionos.com/lnk/)

In the message window of my email I clicked Attach, using the drop down for FileLink - WebDav and selecting my attachment. It uploaded and the message window was populated automatically with the text:

"I've linked 1 file to this email:
 filename.mp4 (x MB) hosted on WebDAV: https://hidrive.ionos.com/lnk/filename.mp4"

which gives anyone access to a shared copy of the named file in the "shared" section. The original is in your personal folder.

This next step is, I think, optional and only necessary if you want to obfuscate the link a bit.
I then went to my HiDrive  via the web app (or your phone app?) and found the file in the shared section, showing an "active" share, and clicked the pencil to "edit the share" and then copied the obfuscated link into the email, to replace the link with the filename.

hence changing the email text to:
" I've linked 1 file to this email:
* filename.mp4 (x MB) hosted on WebDAV: https://hidrive.ionos.com/lnk/abcdef1234 "

This took me HOURS!!
If it saves you some time then I'm happy.
